# Generated by Django 5.1.2 on 2025-11-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, help_text='Elevation in meters', null=True)),
                ('timezone', models.CharField(default='Africa/Cairo', max_length=50)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
                ('average_temperature_summer', models.IntegerField(blank=True, null=True)),
                ('average_temperature_winter', models.IntegerField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_capital', models.BooleanField(default=False)),
                ('has_airport', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.TextField(blank=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('attraction_type', models.CharField(choices=[('historical', 'Historical Site'), ('museum', 'Museum'), ('religious', 'Religious Site'), ('natural', 'Natural Wonder'), ('beach', 'Beach'), ('market', 'Market/Bazaar'), ('modern', 'Modern Attraction'), ('archaeological', 'Archaeological Site')], max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('admission_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('visit_duration', models.CharField(blank=True, help_text='e.g., 2-3 hours', max_length=50)),
                ('is_unesco', models.BooleanField(default=False)),
                ('is_must_see', models.BooleanField(default=False)),
                ('is_family_friendly', models.BooleanField(default=True)),
                ('accessibility_info', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.city')),
            ],
            options={
                'ordering': ['-is_must_see', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='destinations.country'),
        ),
        migrations.CreateModel(
            name='TravelGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('is_transportation', models.BooleanField(default=False)),
                ('is_accommodation', models.BooleanField(default=False)),
                ('is_food', models.BooleanField(default=False)),
                ('is_safety', models.BooleanField(default=False)),
                ('is_culture', models.BooleanField(default=False)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='destinations.city')),
            ],
        ),
    ]
