# Generated by Django 5.1.2 on 2025-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (Unsplash, etc.)', max_length=500, null=True),
        ),
    ]
