# Generated by Django 5.1.2 on 2025-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_city_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', max_length=500, null=True),
        ),
    ]
