[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput",
    "python manage.py setup_site"
]

[start]
cmd = "gunicorn Egy360.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
