[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn Egy360.wsgi --log-file -"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
