# FORCE DEPLOY Dec 11 2025 - Blog content population on production
[build]
builder = "nixpacks"

[deploy]
startCommand = "chmod +x startup.sh && ./startup.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
