# Generated by Django 5.1.2 on 2025-12-23 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_clicks', models.IntegerField(default=0)),
                ('accommodation_clicks', models.IntegerField(default=0)),
                ('tour_clicks', models.IntegerField(default=0)),
                ('flight_clicks', models.IntegerField(default=0)),
                ('other_clicks', models.IntegerField(default=0)),
                ('booking_com_clicks', models.IntegerField(default=0)),
                ('viator_clicks', models.IntegerField(default=0)),
                ('other_platform_clicks', models.IntegerField(default=0)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confirmed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Revenue Summary',
                'verbose_name_plural': 'Daily Revenue Summaries',
                'db_table': 'daily_revenue_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('platform', models.CharField(choices=[('booking_com', 'Booking.com'), ('hotellook', 'Hotellook'), ('agoda', 'Agoda'), ('hotels_com', 'Hotels.com'), ('viator', 'Viator'), ('getyourguide', 'GetYourGuide'), ('travelpayouts', 'Travelpayouts'), ('aviasales', 'Aviasales'), ('discovercars', 'Discovercars'), ('world_nomads', 'World Nomads'), ('direct', 'Direct Booking'), ('other', 'Other')], max_length=50)),
                ('item_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('tour', 'Tour'), ('flight', 'Flight'), ('transportation', 'Transportation'), ('insurance', 'Insurance'), ('car_rental', 'Car Rental')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('affiliate_url', models.URLField(max_length=1000)),
                ('referrer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated commission if booking completes', max_digits=10, null=True)),
                ('converted', models.BooleanField(default=False, help_text='Whether this click resulted in a confirmed booking')),
                ('conversion_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual commission earned if converted', max_digits=10, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affiliate Click',
                'verbose_name_plural': 'Affiliate Clicks',
                'db_table': 'affiliate_clicks',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['platform'], name='affiliate_platform_idx'), models.Index(fields=['item_type'], name='affiliate_item_type_idx'), models.Index(fields=['clicked_at'], name='affiliate_clicked_idx'), models.Index(fields=['user'], name='affiliate_user_idx'), models.Index(fields=['converted'], name='affiliate_converted_idx')],
            },
        ),
    ]
