# Generated by Django 5.1.2 on 2025-12-28 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_datasynclog_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateclick',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='Campaign name: egypt_tours_jan2025, pyramids_promo, etc.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='utm_content',
            field=models.CharField(blank=True, help_text='Content identifier: pyramids_reel, hotel_carousel, etc.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='Traffic medium: social, cpc, email, referral, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='affiliateclick',
            name='utm_source',
            field=models.CharField(blank=True, help_text='Traffic source: instagram, facebook, tiktok, google, etc.', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['utm_source'], name='affiliate_utm_source_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['utm_campaign'], name='affiliate_utm_campaign_idx'),
        ),
    ]
