# Generated by Django 5.1.2 on 2025-11-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL to hotel image (from Booking.com, etc.)', max_length=500, null=True),
        ),
    ]
