# Generated by Django 5.1.2 on 2025-11-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodation_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='agoda_url',
            field=models.URLField(blank=True, help_text='Agoda affiliate URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='booking_com_id',
            field=models.CharField(blank=True, help_text='Booking.com property ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='booking_com_url',
            field=models.URLField(blank=True, help_text='Full Booking.com affiliate URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected commission % (e.g., 4.0 for 4%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='direct_booking_url',
            field=models.URLField(blank=True, help_text="Hotel's direct booking URL", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='hotels_com_url',
            field=models.URLField(blank=True, help_text='Hotels.com affiliate URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='total_bookings',
            field=models.IntegerField(default=0, help_text='Total bookings through this site'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='total_commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total commission earned ($)', max_digits=10),
        ),
    ]
