# Generated by Django 5.1.2 on 2025-12-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_accommodation_agoda_url_accommodation_booking_com_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['city'], name='accommodation_city_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['accommodation_type'], name='accommodation_type_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['is_active'], name='accommodation_active_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['is_featured'], name='accommodation_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['city', 'is_active', 'accommodation_type'], name='accommodation_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['average_rating'], name='accommodation_rating_idx'),
        ),
    ]
