# Generated by Django 5.1.2 on 2025-11-08 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tour_type', models.CharField(choices=[('cultural', 'Cultural & Historical'), ('adventure', 'Adventure'), ('desert', 'Desert Safari'), ('cruise', 'Nile Cruise'), ('diving', 'Diving & Snorkeling'), ('religious', 'Religious'), ('luxury', 'Luxury'), ('budget', 'Budget')], max_length=20)),
                ('description', models.TextField()),
                ('highlights', models.TextField()),
                ('duration_days', models.IntegerField(default=1)),
                ('duration_nights', models.IntegerField(default=0)),
                ('departure_city', models.CharField(max_length=100)),
                ('destinations', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('min_group_size', models.IntegerField(default=1)),
                ('max_group_size', models.IntegerField(default=20)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('includes', models.JSONField(default=list)),
                ('excludes', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('booking_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('tour_date', models.DateField()),
                ('number_of_adults', models.IntegerField(default=1)),
                ('number_of_children', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to='tours.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meals_included', models.CharField(blank=True, max_length=100)),
                ('overnight_location', models.CharField(blank=True, max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour')),
            ],
            options={
                'verbose_name_plural': 'Tour Itineraries',
                'ordering': ['day'],
            },
        ),
    ]
