# Generated by Django 5.1.2 on 2025-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Expected commission % (e.g., 8.0 for 8%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tour',
            name='getyourguide_url',
            field=models.URLField(blank=True, help_text='GetYourGuide affiliate URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL to tour image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_affiliate_clicks',
            field=models.IntegerField(default=0, help_text='Total clicks to affiliate links'),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total commission earned ($)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='travelpayouts_url',
            field=models.URLField(blank=True, help_text='Travelpayouts tours URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='viator_url',
            field=models.URLField(blank=True, help_text='Viator affiliate URL', max_length=500, null=True),
        ),
    ]
