# Generated by Django 5.1.2 on 2025-12-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_commission_rate_tour_getyourguide_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['tour_type'], name='tour_type_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active'], name='tour_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_featured'], name='tour_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['departure_city'], name='tour_departure_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['average_rating'], name='tour_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active', 'tour_type'], name='tour_filter_idx'),
        ),
    ]
