# Generated by Django 5.1.2 on 2025-12-27 19:04
# Data migration to clean blog post content

import re
from django.db import migrations


def clean_content(text):
    """Remove markdown formatting and special characters"""
    if not text:
        return text

    # Remove markdown headers (## ### etc)
    text = re.sub(r'^#{1,6}\s*', '', text, flags=re.MULTILINE)

    # Remove bold/italic markers
    text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
    text = re.sub(r'\*([^*]+)\*', r'\1', text)
    text = re.sub(r'__([^_]+)__', r'\1', text)
    text = re.sub(r'_([^_]+)_', r'\1', text)

    # Remove markdown links [text](url) -> text
    text = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', text)

    # Convert markdown tables to readable format
    text = re.sub(r'^\s*\|[-:| ]+\|\s*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\|\s*', '', text)

    # Remove special Unicode characters
    replacements = {
        '\u2192': ' - ',  # right arrow
        '\u2190': ' - ',  # left arrow
        '\u2191': '',     # up arrow
        '\u2193': '',     # down arrow
        '\u25ba': '',     # play
        '\u25b6': '',     # play
        '\u25cf': '-',    # bullet
        '\u2022': '-',    # bullet
        '\u25aa': '-',    # small square
        '\u2713': 'Yes',  # checkmark
        '\u2717': 'No',   # x mark
        '\u2605': '*',    # star
        '\u2606': '*',    # star outline
        '\u2014': '-',    # em dash
        '\u2013': '-',    # en dash
        '\u201c': '"',    # left quote
        '\u201d': '"',    # right quote
        '\u2018': "'",    # left single quote
        '\u2019': "'",    # right single quote
        '\u2026': '...',  # ellipsis
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    # Remove code blocks
    text = re.sub(r'```[^`]*```', '', text, flags=re.DOTALL)
    text = re.sub(r'`([^`]+)`', r'\1', text)

    # Clean up extra whitespace
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r' +\n', '\n', text)
    text = re.sub(r'\n +', '\n', text)

    return text.strip()


def clean_all_posts(apps, schema_editor):
    """Clean all blog post content"""
    BlogPost = apps.get_model('blog', 'BlogPost')
    posts = BlogPost.objects.all()

    for post in posts:
        original = post.content
        cleaned = clean_content(original)
        if original != cleaned:
            post.content = cleaned
            post.save()


def reverse_clean(apps, schema_editor):
    """Reverse operation - does nothing as we can't restore original"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_image_url'),
    ]

    operations = [
        migrations.RunPython(clean_all_posts, reverse_clean),
    ]
