# Generated by Django 5.1.2 on 2026-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_seed_pyramid_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('story', 'True Story'), ('history', 'Historical'), ('culture', 'Culture'), ('guide', 'Travel Guide'), ('video', 'Video Post'), ('gallery', 'Photo Gallery')], default='article', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='gallery_images',
            field=models.TextField(blank=True, help_text='JSON array of image URLs for galleries', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_video_post',
            field=models.BooleanField(default=False, help_text='Featured as video content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_thumbnail',
            field=models.URLField(blank=True, help_text='Video thumbnail image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Vimeo embed URL', max_length=500, null=True),
        ),
    ]
