# Generated by Django 5.1.2 on 2026-02-18 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_blogpost_content_type_blogpost_gallery_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pinterest', 'Pinterest'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20, unique=True)),
                ('posts_per_day', models.IntegerField(default=1)),
                ('posting_times', models.JSONField(default=list, help_text='UTC times, e.g. ["09:00", "14:00", "19:00"]')),
                ('days_of_week', models.JSONField(default=list, help_text='Day numbers (0=Mon, 6=Sun), e.g. [0,1,2,3,4,5,6]')),
                ('daily_limit', models.IntegerField(default=10, help_text='Hard daily rate limit')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posting Schedule',
                'verbose_name_plural': 'Posting Schedules',
                'db_table': 'posting_schedules',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pinterest', 'Pinterest'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20, unique=True)),
                ('account_name', models.CharField(help_text='Display name', max_length=200)),
                ('account_id', models.CharField(blank=True, help_text='Platform-specific account/page ID', max_length=200)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('platform_metadata', models.JSONField(blank=True, default=dict, help_text='Platform config: board_id, page_id, ig_user_id, app_id, app_secret')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
            },
        ),
        migrations.CreateModel(
            name='SocialPostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('generate', 'Queue Generation'), ('post', 'Post Execution'), ('refresh', 'Token Refresh'), ('metrics', 'Metrics Update')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('posts_processed', models.IntegerField(default=0)),
                ('posts_succeeded', models.IntegerField(default=0)),
                ('posts_failed', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Social Post Log',
                'verbose_name_plural': 'Social Post Logs',
                'db_table': 'social_post_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('pinterest', 'Pinterest'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('caption', models.TextField(help_text='Platform-optimized caption')),
                ('hashtags', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('utm_url', models.URLField(help_text='Article URL with UTM tracking', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('posting', 'Posting...'), ('posted', 'Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('posted_time', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=200)),
                ('post_url', models.URLField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('impressions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'db_table': 'social_posts',
                'ordering': ['-scheduled_time', '-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_time'], name='social_post_queue_idx'), models.Index(fields=['platform', 'status'], name='social_post_platform_idx'), models.Index(fields=['blog_post', 'platform'], name='social_post_blog_plat_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'posted', 'posting'])), fields=('blog_post', 'platform'), name='unique_active_post_per_platform')],
            },
        ),
    ]
