# Generated by Django 5.1.2 on 2026-01-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_query_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_user_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_status_pay_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_created_idx',
        ),
    ]
