"""
Management command to add 30+ more Egyptian tours
Covers various categories: cultural, adventure, desert, diving, luxury
"""
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from tours.models import Tour
from decimal import Decimal


class Command(BaseCommand):
    help = 'Populate database with 30+ additional Egyptian tours'

    def handle(self, *args, **options):
        self.stdout.write('Adding more Egyptian tours...')

        tours = [
            # MULTI-DAY TOURS
            {
                'name': 'Complete Egypt Explorer - 10 Days',
                'tour_type': 'cultural',
                'description': 'The ultimate Egypt experience covering Cairo, Luxor, Aswan, and Abu Simbel. Includes pyramids, temples, Nile cruise, and desert adventures. Perfect for first-time visitors wanting to see it all.',
                'highlights': 'Pyramids of Giza, Egyptian Museum, Valley of the Kings, Karnak Temple, Abu Simbel, 4-night Nile Cruise, Philae Temple, Aswan High Dam',
                'duration_days': 10,
                'duration_nights': 9,
                'departure_city': 'Cairo',
                'destinations': ['Cairo', 'Luxor', 'Aswan', 'Abu Simbel'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('1850.00'),
                'includes': ['Domestic flights', '5-star hotels', 'Nile cruise', 'All entrance fees', 'Expert guide', 'All meals on cruise'],
                'excludes': ['International flights', 'Travel insurance', 'Personal expenses', 'Tips'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 487,
            },
            {
                'name': 'Nile Cruise Luxor to Aswan - 4 Days',
                'tour_type': 'cruise',
                'description': 'Classic Nile cruise aboard a 5-star vessel from Luxor to Aswan. Visit ancient temples, enjoy onboard entertainment, and watch the timeless landscape drift by.',
                'highlights': 'Luxor Temple, Karnak Temple, Valley of the Kings, Edfu Temple, Kom Ombo Temple, Philae Temple, Felucca ride',
                'duration_days': 4,
                'duration_nights': 3,
                'departure_city': 'Luxor',
                'destinations': ['Luxor', 'Edfu', 'Kom Ombo', 'Aswan'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('550.00'),
                'includes': ['5-star cruise cabin', 'Full board meals', 'Temple visits', 'Egyptologist guide', 'Entertainment'],
                'excludes': ['Drinks', 'Optional excursions', 'Tips'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 1234,
            },
            {
                'name': 'Cairo and Alexandria - 5 Days',
                'tour_type': 'cultural',
                'description': 'Explore Egypt\'s two greatest cities. From the ancient pyramids to the Mediterranean charm of Alexandria, discover 5000 years of history.',
                'highlights': 'Pyramids of Giza, Sphinx, Egyptian Museum, Alexandria Library, Catacombs, Citadel of Qaitbay, Montaza Palace',
                'duration_days': 5,
                'duration_nights': 4,
                'departure_city': 'Cairo',
                'destinations': ['Cairo', 'Giza', 'Alexandria'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('680.00'),
                'includes': ['4-star hotels', 'Private transport', 'All entrance fees', 'Egyptologist guide', 'Breakfast daily'],
                'excludes': ['Lunches and dinners', 'Tips', 'Personal expenses'],
                'average_rating': Decimal('4.7'),
                'total_reviews': 876,
            },

            # DESERT & ADVENTURE TOURS
            {
                'name': 'White Desert Overnight Safari',
                'tour_type': 'desert',
                'description': 'Journey to Egypt\'s most surreal landscape - the White Desert. Camp under millions of stars surrounded by chalk rock formations shaped by millennia of wind.',
                'highlights': 'Black Desert, Crystal Mountain, White Desert, Bedouin dinner, Desert camping, Sunrise over white rocks',
                'duration_days': 2,
                'duration_nights': 1,
                'departure_city': 'Cairo',
                'destinations': ['Bahariya Oasis', 'White Desert'],
                'difficulty_level': 'moderate',
                'price_per_person': Decimal('180.00'),
                'includes': ['4x4 jeep transport', 'Camping equipment', 'Bedouin dinner and breakfast', 'Guide', 'Permits'],
                'excludes': ['Sleeping bag rental', 'Tips', 'Personal items'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 2341,
            },
            {
                'name': 'Siwa Oasis Adventure - 3 Days',
                'tour_type': 'adventure',
                'description': 'Discover the remote Siwa Oasis, a Berber paradise in the Western Desert. Hot springs, salt lakes, ancient ruins, and untouched culture await.',
                'highlights': 'Temple of the Oracle, Cleopatra\'s Spring, Great Sand Sea, Shali Fortress, Salt lakes, Desert sunset',
                'duration_days': 3,
                'duration_nights': 2,
                'departure_city': 'Cairo',
                'destinations': ['Siwa Oasis'],
                'difficulty_level': 'moderate',
                'price_per_person': Decimal('320.00'),
                'includes': ['Transport', 'Eco-lodge accommodation', 'Meals', 'Desert safari', 'Guide'],
                'excludes': ['Tips', 'Personal expenses', 'Hot spring entry'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 654,
            },
            {
                'name': 'Mount Sinai Sunrise Trek',
                'tour_type': 'adventure',
                'description': 'Climb the sacred Mount Sinai overnight to witness an unforgettable sunrise. Visit St. Catherine\'s Monastery, one of the world\'s oldest.',
                'highlights': 'Mount Sinai summit, Sunrise over Sinai, St. Catherine Monastery, Burning Bush, Bedouin tea',
                'duration_days': 2,
                'duration_nights': 1,
                'departure_city': 'Sharm El Sheikh',
                'destinations': ['Mount Sinai', 'St. Catherine'],
                'difficulty_level': 'challenging',
                'price_per_person': Decimal('85.00'),
                'includes': ['Transport', 'Bedouin guide', 'Monastery visit', 'Breakfast', 'Blankets'],
                'excludes': ['Tips', 'Camel ride (optional)', 'Personal items'],
                'average_rating': Decimal('4.7'),
                'total_reviews': 1876,
            },

            # DIVING TOURS
            {
                'name': 'Red Sea Diving Safari - 7 Days',
                'tour_type': 'diving',
                'description': 'Live-aboard diving adventure to Egypt\'s best dive sites. Explore pristine reefs, shipwrecks, and marine life in the Red Sea.',
                'highlights': 'Ras Mohammed, Thistlegorm Wreck, Shark Reef, Brothers Islands, Elphinstone Reef, 18+ dives',
                'duration_days': 7,
                'duration_nights': 6,
                'departure_city': 'Hurghada',
                'destinations': ['Red Sea'],
                'difficulty_level': 'moderate',
                'price_per_person': Decimal('1200.00'),
                'includes': ['Live-aboard boat', 'Full board', '18 dives', 'Tanks and weights', 'Dive guide', 'Marine park fees'],
                'excludes': ['Equipment rental', 'Nitrox', 'Tips', 'Flights'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 432,
            },
            {
                'name': 'Dahab Blue Hole Diving Day',
                'tour_type': 'diving',
                'description': 'Dive the legendary Blue Hole, one of the world\'s most famous dive sites. Suitable for certified divers of all levels.',
                'highlights': 'Blue Hole dive, Canyon dive, Bedouin lunch, Dahab coastline',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Dahab',
                'destinations': ['Dahab'],
                'difficulty_level': 'moderate',
                'price_per_person': Decimal('75.00'),
                'includes': ['2 dives', 'Equipment', 'Dive guide', 'Lunch', 'Transport'],
                'excludes': ['Tips', 'Photos'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 987,
            },
            {
                'name': 'Learn to Dive - PADI Open Water',
                'tour_type': 'diving',
                'description': 'Get certified in the crystal-clear Red Sea. 4-day PADI Open Water course with experienced instructors in Sharm El Sheikh.',
                'highlights': 'PADI certification, 4 open water dives, Pool training, Theory lessons, Lifetime certification',
                'duration_days': 4,
                'duration_nights': 0,
                'departure_city': 'Sharm El Sheikh',
                'destinations': ['Sharm El Sheikh'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('350.00'),
                'includes': ['PADI materials', 'All equipment', 'Certification fee', 'Instructor', 'Pool and sea dives'],
                'excludes': ['Accommodation', 'Meals', 'Tips'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 1543,
            },

            # DAY TOURS FROM CAIRO
            {
                'name': 'Pyramids, Sphinx & Egyptian Museum',
                'tour_type': 'cultural',
                'description': 'The essential Cairo day tour covering the must-see ancient wonders. Enter the Great Pyramid, meet the Sphinx, and explore 5000 years of treasures.',
                'highlights': 'Great Pyramid of Giza, Sphinx, Valley Temple, Egyptian Museum, Tutankhamun treasures',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Cairo',
                'destinations': ['Giza', 'Cairo'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('65.00'),
                'includes': ['Hotel pickup', 'Egyptologist guide', 'Entrance fees', 'Lunch', 'Air-conditioned vehicle'],
                'excludes': ['Tips', 'Pyramid entry (optional)', 'Personal expenses'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 4567,
            },
            {
                'name': 'Memphis, Saqqara & Dahshur Pyramids',
                'tour_type': 'cultural',
                'description': 'Escape the crowds and explore Egypt\'s lesser-known but equally impressive pyramid sites. Includes the Step Pyramid and Red Pyramid.',
                'highlights': 'Step Pyramid of Djoser, Red Pyramid (enter free!), Bent Pyramid, Memphis open-air museum, Ramses II statue',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Cairo',
                'destinations': ['Saqqara', 'Dahshur', 'Memphis'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('55.00'),
                'includes': ['Hotel pickup', 'Guide', 'Entrance fees', 'Lunch', 'Transport'],
                'excludes': ['Tips', 'Personal expenses'],
                'average_rating': Decimal('4.7'),
                'total_reviews': 1234,
            },
            {
                'name': 'Islamic Cairo Walking Tour',
                'tour_type': 'cultural',
                'description': 'Discover medieval Cairo\'s mosques, madrasas, and markets. Walk through centuries of Islamic architecture and history.',
                'highlights': 'Al-Azhar Mosque, Khan el-Khalili bazaar, Sultan Hassan Mosque, Citadel of Saladin, Muizz Street',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Cairo',
                'destinations': ['Cairo'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('45.00'),
                'includes': ['Guide', 'Mosque entries', 'Traditional lunch', 'Tea break'],
                'excludes': ['Transport', 'Shopping', 'Tips'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 876,
            },
            {
                'name': 'Grand Egyptian Museum VIP Tour',
                'tour_type': 'cultural',
                'description': 'Skip-the-line access to the world\'s largest archaeological museum. See the complete Tutankhamun collection and thousands of artifacts.',
                'highlights': 'Complete Tutankhamun collection, Royal Mummies Hall, Grand Staircase, Pyramid views, Conservation center',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Cairo',
                'destinations': ['Giza'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('95.00'),
                'includes': ['Skip-the-line entry', 'Egyptologist guide', 'Transport', 'Lunch'],
                'excludes': ['Tips', 'Photography permits', 'Personal expenses'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 765,
            },

            # LUXOR DAY TOURS
            {
                'name': 'Luxor West Bank Full Day',
                'tour_type': 'cultural',
                'description': 'Explore the ancient Theban necropolis. Visit royal tombs, magnificent temples, and discover why Luxor is called the world\'s greatest open-air museum.',
                'highlights': 'Valley of the Kings (3 tombs), Hatshepsut Temple, Colossi of Memnon, Valley of the Queens, Medinet Habu',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Luxor',
                'destinations': ['Luxor West Bank'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('70.00'),
                'includes': ['Hotel pickup', 'Guide', 'Entrance fees', 'Lunch', 'Transport'],
                'excludes': ['Tutankhamun tomb (extra)', 'Tips', 'Personal expenses'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 2341,
            },
            {
                'name': 'Luxor Hot Air Balloon Sunrise',
                'tour_type': 'adventure',
                'description': 'Float over the Valley of the Kings at sunrise. See ancient temples and the Nile from above in this unforgettable experience.',
                'highlights': 'Sunrise flight, Valley of Kings aerial view, Hatshepsut Temple from above, Nile River views, Photo opportunities',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Luxor',
                'destinations': ['Luxor'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('110.00'),
                'includes': ['Hotel pickup', 'Balloon flight (45-60 min)', 'Breakfast', 'Flight certificate'],
                'excludes': ['Tips', 'Photos/videos', 'Personal insurance'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 3456,
            },
            {
                'name': 'Karnak & Luxor Temple Night Tour',
                'tour_type': 'cultural',
                'description': 'Experience ancient temples under the stars. See the spectacular Sound & Light show at Karnak Temple.',
                'highlights': 'Karnak Temple at night, Sound & Light show, Luxor Temple illuminated, Avenue of Sphinxes',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Luxor',
                'destinations': ['Luxor'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('55.00'),
                'includes': ['Transport', 'Guide', 'Sound & Light ticket', 'Temple entries'],
                'excludes': ['Dinner', 'Tips', 'Personal expenses'],
                'average_rating': Decimal('4.6'),
                'total_reviews': 987,
            },

            # ASWAN TOURS
            {
                'name': 'Abu Simbel Day Trip from Aswan',
                'tour_type': 'cultural',
                'description': 'Visit the colossal temples of Ramses II at Abu Simbel. Marvel at the engineering feat that moved these temples to save them from flooding.',
                'highlights': 'Great Temple of Ramses II, Temple of Nefertari, UNESCO World Heritage Site, Lake Nasser views',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Aswan',
                'destinations': ['Abu Simbel'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('85.00'),
                'includes': ['Transport', 'Guide', 'Entrance fees', 'Breakfast box', 'Water'],
                'excludes': ['Tips', 'Lunch', 'Personal expenses'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 2134,
            },
            {
                'name': 'Aswan Highlights & Felucca Sunset',
                'tour_type': 'cultural',
                'description': 'Discover Aswan\'s treasures and end with a magical felucca sail at sunset. See ancient temples and experience Nubian culture.',
                'highlights': 'Philae Temple, High Dam, Unfinished Obelisk, Felucca sunset sail, Nubian village visit',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Aswan',
                'destinations': ['Aswan'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('60.00'),
                'includes': ['Transport', 'Guide', 'Entrance fees', 'Felucca ride', 'Nubian tea'],
                'excludes': ['Lunch', 'Tips', 'Personal expenses'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 1543,
            },

            # LUXURY TOURS
            {
                'name': 'Private Egypt Luxury Tour - 8 Days',
                'tour_type': 'luxury',
                'description': 'The ultimate luxury Egypt experience. Private jet transfers, 5-star accommodations, exclusive access to monuments, and personal Egyptologist.',
                'highlights': 'Private pyramid tour, Luxury Nile cruise, Abu Simbel by private plane, Royal Mummies VIP access, Fine dining experiences',
                'duration_days': 8,
                'duration_nights': 7,
                'departure_city': 'Cairo',
                'destinations': ['Cairo', 'Luxor', 'Aswan', 'Abu Simbel'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('5500.00'),
                'includes': ['Private jet', '5-star hotels', 'Luxury cruise', 'All meals', 'Private Egyptologist', 'VIP access'],
                'excludes': ['International flights', 'Travel insurance', 'Personal shopping'],
                'average_rating': Decimal('5.0'),
                'total_reviews': 89,
            },
            {
                'name': 'Dahabiya Nile Cruise - 5 Days',
                'tour_type': 'luxury',
                'description': 'Sail the Nile in style aboard a traditional dahabiya (sailing boat). Intimate experience with gourmet food and exclusive temple visits.',
                'highlights': 'Traditional sailing, Gourmet cuisine, Private temple visits, Sunset cocktails, Swimming in the Nile',
                'duration_days': 5,
                'duration_nights': 4,
                'departure_city': 'Luxor',
                'destinations': ['Luxor', 'Esna', 'Edfu', 'Aswan'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('1800.00'),
                'includes': ['Dahabiya cabin', 'All meals & drinks', 'Temple visits', 'Egyptologist', 'Transfers'],
                'excludes': ['Tips', 'Personal expenses', 'Optional excursions'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 234,
            },

            # RED SEA TOURS
            {
                'name': 'Hurghada Snorkeling Trip',
                'tour_type': 'diving',
                'description': 'Discover the underwater wonders of the Red Sea without diving. Visit pristine coral reefs teeming with tropical fish.',
                'highlights': 'Giftun Island, Coral reefs, Tropical fish, Beach time, Snorkeling equipment',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Hurghada',
                'destinations': ['Giftun Island'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('35.00'),
                'includes': ['Boat trip', 'Snorkeling equipment', 'Lunch', 'Soft drinks', 'Marine park fees'],
                'excludes': ['Tips', 'Photos', 'Towels'],
                'average_rating': Decimal('4.6'),
                'total_reviews': 3421,
            },
            {
                'name': 'Hurghada Desert Safari & BBQ',
                'tour_type': 'desert',
                'description': 'Experience the Eastern Desert with quad biking, camel riding, and traditional Bedouin BBQ dinner under the stars.',
                'highlights': 'Quad biking, Camel ride, Bedouin village, BBQ dinner, Stargazing, Belly dance show',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Hurghada',
                'destinations': ['Eastern Desert'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('45.00'),
                'includes': ['Quad bike', 'Camel ride', 'BBQ dinner', 'Soft drinks', 'Entertainment', 'Transport'],
                'excludes': ['Tips', 'Alcoholic drinks', 'Photos'],
                'average_rating': Decimal('4.5'),
                'total_reviews': 2876,
            },
            {
                'name': 'Swimming with Dolphins Hurghada',
                'tour_type': 'adventure',
                'description': 'Swim alongside wild dolphins in their natural habitat. An ethical encounter with spinner dolphins in the Red Sea.',
                'highlights': 'Wild dolphin encounter, Snorkeling, Coral reef visit, Professional guide, Photo opportunities',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Hurghada',
                'destinations': ['Red Sea'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('55.00'),
                'includes': ['Boat trip', 'Snorkeling gear', 'Guide', 'Lunch', 'Soft drinks'],
                'excludes': ['Tips', 'Wetsuit rental', 'Photos'],
                'average_rating': Decimal('4.7'),
                'total_reviews': 1654,
            },

            # SPECIAL INTEREST
            {
                'name': 'Egypt Photography Tour - 10 Days',
                'tour_type': 'cultural',
                'description': 'Designed for photographers. Visit the best locations at optimal times with a professional photographer guide. Includes exclusive access.',
                'highlights': 'Golden hour shoots, Night photography, Exclusive access, Professional guidance, Portfolio review',
                'duration_days': 10,
                'duration_nights': 9,
                'departure_city': 'Cairo',
                'destinations': ['Cairo', 'Luxor', 'Aswan', 'Alexandria'],
                'difficulty_level': 'moderate',
                'price_per_person': Decimal('2800.00'),
                'includes': ['4-star hotels', 'Photo guide', 'Transport', 'Special access permits', 'Breakfast'],
                'excludes': ['Camera equipment', 'International flights', 'Tips'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 167,
            },
            {
                'name': 'Egyptian Cooking Class Cairo',
                'tour_type': 'cultural',
                'description': 'Learn to cook authentic Egyptian dishes in a traditional Cairo home. Market tour included, then hands-on cooking with local chef.',
                'highlights': 'Local market visit, Hands-on cooking, Traditional recipes, Egyptian hospitality, Recipe book',
                'duration_days': 1,
                'duration_nights': 0,
                'departure_city': 'Cairo',
                'destinations': ['Cairo'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('65.00'),
                'includes': ['Market tour', 'Ingredients', 'Cooking class', 'Full meal', 'Recipe book', 'Drinks'],
                'excludes': ['Transport', 'Tips'],
                'average_rating': Decimal('4.9'),
                'total_reviews': 432,
            },
            {
                'name': 'Ancient Egypt for Families - 7 Days',
                'tour_type': 'cultural',
                'description': 'Kid-friendly Egypt adventure designed for families. Interactive tours, mummy-making workshops, and experiences children will love.',
                'highlights': 'Interactive pyramid tour, Mummy workshop, Felucca sailing, Camel riding, Kid-friendly guides',
                'duration_days': 7,
                'duration_nights': 6,
                'departure_city': 'Cairo',
                'destinations': ['Cairo', 'Luxor', 'Aswan'],
                'difficulty_level': 'easy',
                'price_per_person': Decimal('1100.00'),
                'includes': ['Family rooms', 'Kid-friendly guides', 'All entrance fees', 'Activities', 'Breakfast'],
                'excludes': ['International flights', 'Lunches/dinners', 'Tips'],
                'average_rating': Decimal('4.8'),
                'total_reviews': 543,
            },
        ]

        # Travelpayouts marker
        marker = '477897'

        created_count = 0
        for tour in tours:
            slug = slugify(tour['name'])

            # Generate Viator affiliate URL
            tour_name_encoded = tour['name'].replace(' ', '+')
            viator_url = f"https://www.viator.com/searchResults/all?text={tour_name_encoded}&destId=722&currency=USD"
            travelpayouts_url = f"https://tp.media/click?shmarker={marker}&campaign_id=97&searchType=1&city=Egypt&q={tour_name_encoded}"

            obj, created = Tour.objects.update_or_create(
                slug=slug,
                defaults={
                    'name': tour['name'],
                    'tour_type': tour['tour_type'],
                    'description': tour['description'],
                    'highlights': tour['highlights'],
                    'duration_days': tour['duration_days'],
                    'duration_nights': tour['duration_nights'],
                    'departure_city': tour['departure_city'],
                    'destinations': tour['destinations'],
                    'difficulty_level': tour['difficulty_level'],
                    'price_per_person': tour['price_per_person'],
                    'includes': tour['includes'],
                    'excludes': tour['excludes'],
                    'average_rating': tour['average_rating'],
                    'total_reviews': tour['total_reviews'],
                    'viator_url': viator_url,
                    'travelpayouts_url': travelpayouts_url,
                    'commission_rate': Decimal('8.0'),
                    'is_active': True,
                    'is_featured': tour['average_rating'] >= Decimal('4.9'),
                }
            )

            if created:
                created_count += 1
                self.stdout.write(f'  Created: {obj.name}')
            else:
                self.stdout.write(f'  Updated: {obj.name}')

        self.stdout.write(self.style.SUCCESS(f'\nAdded {created_count} new tours (total: {len(tours)})'))
